### PR TITLE
Hyperlink DOIs against preferred resolver

### PR DESCRIPTION
**Pull request by katrinleinweber**
Hello :-)

The DOI foundation recommends [this new, secure resolver](https://www.doi.org/doi_handbook/3_Resolution.html#3.8) and Zenodo started using it for its badges as well. Accordingly, this PR updates all DOI links.

Cheers!

### CODE REVIEW

**Comment by jkitchin** [comment]
Thanks for commenting on this. This is probably the wrong place to fix this, because when I publish I force push to this repo. Did you use some sed-fu to do this?

**Comment by katrinleinweber** [comment]
Yes, I use [a Bash script](https://gist.github.com/katrinleinweber/2c76d9f763f135b76b4440268603d862/edit).

Do you generate the website from the contents of your other repos? I could send PRs to them as well, like https://github.com/jkitchin/scimax-win-elpa/pull/1.

I'm curious why you `git push` publish with particular `--force`? IMHO, a `git pull --rebase` after merging this on GitHub could easily fit into your workflow.

**Comment by katrinleinweber** [comment]
Would resolving this conflict ensure a merge, or shall I send a PR against the `source` branch?

**Comment by jkitchin** [comment]
Thanks for reporting these. I decided it would be best for me to resolve these with the tools I use to make the blog.

**Comment by katrinleinweber** [comment]
I had hoped GitHub PRs were one of those tools, but you're welcome either way :-)

**Comment by jkitchin** [comment]
I do appreciate it. It was a good opportunity for me to learn something new, make the fixes in smaller chunks, and do some clean up along the way. Thanks for the help!

**Pull request closed without merging**
